package com.Server.controller;

import com.Server.dao.PetServiceImpl;
import com.Server.model.Pet;
import jakarta.persistence.GeneratedValue;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@RestController  // Tells the server there are controller methods in for URL paths
@RequestMapping("/v1")  // Use a prefix for all URL paths to indicate the version of the controller
public class PetApiController {

    // Data members
    PetServiceImpl thePetService;  // Define a refrence to the service to interact with data framework

    // Constructor - Generated by IDE with service refernce which will be dependency injected
    public PetApiController(PetServiceImpl thePetService) {
        this.thePetService = thePetService;
    }

    // Controller to return all the pets in the data source
    // The DAO implementation method that will return what we need:
    //          List<Pet> getAllPets()
    // What will be returned from the controller: List<Pet>
    // What data the controller need to pass to the DAO method and where to get it: None
    // URL path the client will use to run the controller: "/pets"
    //The HTTP method required to run the controller: GET

    @GetMapping("/pets")
    public List<Pet> anyNameYouWant() {
        return thePetService.getAllPets();
    }

    @PostMapping("/pets")
    public Pet addAPet(@RequestBody Pet newPet) {
        return thePetService.addPet(newPet);
    }

}  // End of PetController class
